config/routes.rb
IndividualProjectRestaurant::Application.routes.draw do
  resources :checkouts

  resources :menus

  resources :tickets

end

app/models/checkout.rb
class Checkout < ActiveRecord::Base
  attr_accessible :paid_status, :subtotal, :tax, :ticket_id, :total

  has_many :tickets
  has_many :menus, :through => :tickets

  validates :paid_status, :subtotal, :tax, :total,  presence: true

  before_save do
    total
  end

  def total
    self.total = self.subtotal + self.tax
  end

  def tax
    self.tax = self.subtotal * 0.0825
  end

end

app/models/menu.rb
class Menu < ActiveRecord::Base
  attr_accessible :description, :name, :price

  has_many :tickets
  has_many :checkouts,:through => :tickets

  validates :description, :name, :price, presence: true
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  attr_accessible :kitchen_status, :name, :price, :quantity, :subtotal
  belongs_to :menu
  belongs_to :checkout

  validates :name, :price, :quantity,  presence: true

  before_save do
    subtotal
  end
  def subtotal
    self.subtotal = self.quantity * self.price
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/checkouts_controller.rb
class CheckoutsController < ApplicationController
  # GET /checkouts
  # GET /checkouts.json
  def index
    @checkouts = Checkout.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @checkouts }
    end
  end

  # GET /checkouts/1
  # GET /checkouts/1.json
  def show
    @checkout = Checkout.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @checkout }
    end
  end

  # GET /checkouts/new
  # GET /checkouts/new.json
  def new
    @checkout = Checkout.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @checkout }
    end
  end

  # GET /checkouts/1/edit
  def edit
    @checkout = Checkout.find(params[:id])
  end

  # POST /checkouts
  # POST /checkouts.json
  def create
    @checkout = Checkout.new(params[:checkout])

    respond_to do |format|
      if @checkout.save
        format.html { redirect_to @checkout, notice: 'Checkout was successfully created.' }
        format.json { render json: @checkout, status: :created, location: @checkout }
      else
        format.html { render action: "new" }
        format.json { render json: @checkout.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /checkouts/1
  # PUT /checkouts/1.json
  def update
    @checkout = Checkout.find(params[:id])

    respond_to do |format|
      if @checkout.update_attributes(params[:checkout])
        format.html { redirect_to @checkout, notice: 'Checkout was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @checkout.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /checkouts/1
  # DELETE /checkouts/1.json
  def destroy
    @checkout = Checkout.find(params[:id])
    @checkout.destroy

    respond_to do |format|
      format.html { redirect_to checkouts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  # GET /menus
  # GET /menus.json
  def index
    @menus = Menu.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @menus }
    end
  end

  # GET /menus/1
  # GET /menus/1.json
  def show
    @menu = Menu.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @menu }
    end
  end

  # GET /menus/new
  # GET /menus/new.json
  def new
    @menu = Menu.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @menu }
    end
  end

  # GET /menus/1/edit
  def edit
    @menu = Menu.find(params[:id])
  end

  # POST /menus
  # POST /menus.json
  def create
    @menu = Menu.new(params[:menu])

    respond_to do |format|
      if @menu.save
        format.html { redirect_to @menu, notice: 'Menu was successfully created.' }
        format.json { render json: @menu, status: :created, location: @menu }
      else
        format.html { render action: "new" }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /menus/1
  # PUT /menus/1.json
  def update
    @menu = Menu.find(params[:id])

    respond_to do |format|
      if @menu.update_attributes(params[:menu])
        format.html { redirect_to @menu, notice: 'Menu was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /menus/1
  # DELETE /menus/1.json
  def destroy
    @menu = Menu.find(params[:id])
    @menu.destroy

    respond_to do |format|
      format.html { redirect_to menus_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  # GET /tickets
  # GET /tickets.json
  def index
    @tickets = Ticket.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tickets }
    end
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
    @ticket = Ticket.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ticket }
    end
  end

  # GET /tickets/new
  # GET /tickets/new.json
  def new
    @ticket = Ticket.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ticket }
    end
  end

  # GET /tickets/1/edit
  def edit
    @ticket = Ticket.find(params[:id])
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = Ticket.new(params[:ticket])

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
        format.json { render json: @ticket, status: :created, location: @ticket }
      else
        format.html { render action: "new" }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tickets/1
  # PUT /tickets/1.json
  def update
    @ticket = Ticket.find(params[:id])

    respond_to do |format|
      if @ticket.update_attributes(params[:ticket])
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket = Ticket.find(params[:id])
    @ticket.destroy

    respond_to do |format|
      format.html { redirect_to tickets_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/checkouts_helper.rb
module CheckoutsHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/checkouts/_form.html.erb
<%= form_for(@checkout) do |f| %>
  <% if @checkout.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@checkout.errors.count, "error") %> prohibited this checkout from being saved:</h2>

      <ul>
      <% @checkout.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ticket_id %><br />
    <%= f.collection_select(:ticket_id,Ticket.all,:id,:id) %>
  </div>
  <div class="field">
    <%= f.label :paid_status %><br />
    <%= f.check_box :paid_status %>
  </div>
  <div class="field">
    <%= f.label :subtotal %><br />
    <%= f.collection_select(:subtotal,Ticket.all,:subtotal,:subtotal) %>
  </div>
  <div class="field">
    <%= f.hidden_field :tax, :value => "subtotal" %>
    <%= f.hidden_field :tax, :value => "subtotal"%>
  </div>
  <div class="field">
    <%= f.hidden_field :total, :value => "total" %>
    <%= f.hidden_field :total, :value => "total" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/checkouts/edit.html.erb
<h1>Editing checkout</h1>

<%= render 'form' %>

<%= link_to 'Show', @checkout %> |
<%= link_to 'Back', checkouts_path %>

app/views/checkouts/index.html.erb
<h1>Listing checkouts</h1>

<table>
  <tr>
    <th>Ticket</th>
    <th>Paid status</th>
    <th>Subtotal</th>
    <th>Tax</th>
    <th>Total</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @checkouts.each do |checkout| %>
  <tr>
    <td><%= checkout.ticket_id %></td>
    <td><%= checkout.paid_status %></td>
    <td><%= number_to_currency(checkout.subtotal) %></td>
    <td><%= checkout.tax %></td>
    <td><%= number_to_currency(checkout.total) %></td>
    <td><%= link_to 'Show', checkout %></td>
    <td><%= link_to 'Edit', edit_checkout_path(checkout) %></td>
    <td><%= link_to 'Destroy', checkout, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Checkout', new_checkout_path %>

app/views/checkouts/new.html.erb
<h1>New checkout</h1>

<%= render 'form' %>

<%= link_to 'Back', checkouts_path %>

app/views/checkouts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Ticket:</b>
  <%= @checkout.ticket_id %>
</p>

<p>
  <b>Paid status:</b>
  <%= @checkout.paid_status %>
</p>

<p>
  <b>Subtotal:</b>
  <%= @checkout.subtotal %>
</p>

<p>
  <b>Tax:</b>
  <%= @checkout.tax %>
</p>

<p>
  <b>Total:</b>
  <%= @checkout.total %>
</p>


<%= link_to 'Edit', edit_checkout_path(@checkout) %> |
<%= link_to 'Back', checkouts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IndividualProjectRestaurant</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<h1> Angels Restaurant Order System</h1>
<%=link_to "Menus", menus_path %>
<%=link_to "Tickets", tickets_path %>
<%=link_to "Checkouts", checkouts_path %>
<%= yield %>

</body>
</html>

app/views/menus/_form.html.erb
<%= form_for(@menu) do |f| %>
  <% if @menu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@menu.errors.count, "error") %> prohibited this menu from being saved:</h2>

      <ul>
      <% @menu.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/menus/edit.html.erb
<h1>Editing menu</h1>

<%= render 'form' %>

<%= link_to 'Show', @menu %> |
<%= link_to 'Back', menus_path %>

app/views/menus/index.html.erb
<h1>Listing menus</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Price</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @menus.each do |menu| %>
  <tr>
    <td><%= menu.name %></td>
    <td><%= menu.description %></td>
    <td><%= number_to_currency(menu.price) %></td>
    <td><%= link_to 'Show', menu %></td>
    <td><%= link_to 'Edit', edit_menu_path(menu) %></td>
    <td><%= link_to 'Destroy', menu, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Menu', new_menu_path %>

app/views/menus/new.html.erb
<h1>New menu</h1>

<%= render 'form' %>

<%= link_to 'Back', menus_path %>

app/views/menus/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @menu.name %>
</p>

<p>
  <b>Description:</b>
  <%= @menu.description %>
</p>

<p>
  <b>Price:</b>
  <%= @menu.price %>
</p>


<%= link_to 'Edit', edit_menu_path(@menu) %> |
<%= link_to 'Back', menus_path %>

app/views/tickets/_form.html.erb
<%= form_for(@ticket) do |f| %>
  <% if @ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
      <% @ticket.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.collection_select(:name,Menu.all,:name,:name) %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.collection_select(:price,Menu.all,:price,:price) %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br />
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <%= f.hidden_field :subtotal, :value => "subtotal" %><br />
    <%= f.hidden_field :subtotal, :value => "subtotal" %>
  </div>
  <div class="field">
    <%= f.label :kitchen_status %><br />
    <%= f.check_box :kitchen_status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tickets/edit.html.erb
<h1>Editing ticket</h1>

<%= render 'form' %>

<%= link_to 'Show', @ticket %> |
<%= link_to 'Back', tickets_path %>

app/views/tickets/index.html.erb
<h1>Listing tickets</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Price</th>
    <th>Quantity</th>
    <th>Subtotal</th>
    <th>Kitchen status</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tickets.each do |ticket| %>
  <tr>
    <td><%= ticket.name %></td>
    <td><%= number_to_currency (ticket.price) %></td>
    <td><%= ticket.quantity %></td>
    <td><%= ticket.subtotal %></td>
    <td><%= ticket.kitchen_status %></td>
    <td><%= link_to 'Show', ticket %></td>
    <td><%= link_to 'Edit', edit_ticket_path(ticket) %></td>
    <td><%= link_to 'Destroy', ticket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Ticket', new_ticket_path %>

app/views/tickets/new.html.erb
<h1>New ticket</h1>

<%= render 'form' %>

<%= link_to 'Back', tickets_path %>

app/views/tickets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @ticket.name %>
</p>

<p>
  <b>Price:</b>
  <%= @ticket.price %>
</p>

<p>
  <b>Quantity:</b>
  <%= @ticket.quantity %>
</p>

<p>
  <b>Subtotal:</b>
  <%= @ticket.subtotal %>
</p>

<p>
  <b>Kitchen status:</b>
  <%= @ticket.kitchen_status %>
</p>


<%= link_to 'Edit', edit_ticket_path(@ticket) %> |
<%= link_to 'Back', tickets_path %>